spring.application.name=sellio_backend
spring.datasource.url=jdbc:postgresql://localhost:5432/sellio_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.flyway.enabled=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Storge
storage.key=your key
storage.secret= your secret
storage.endpoint=http://localhost:4566
storage.bucket=bucket name
storage.cdn-endpoint=http://localhost:4566

