spring.application.name=sellio_backend
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.jpa.hibernate.ddl-auto= validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect